resources:
  - name: esh-image
    type: docker-image
    icon: docker
    source:
      repository: registry.barth.tech/library/esh
      username: ((registry.username))
      password: ((registry.password))
  - name: esh-release
    icon: github
    type: github-release
    source:
      owner: jirutka
      repo: esh
      access_token: ((github-access-token))

jobs:
  - name: build-esh
    plan:
      - get: git-repo
        trigger: true
        passed: [update-pipeline]
      - get: esh-release
        trigger: true
      - put: build-status
        params: {state: pending, commit: git-repo}
      - task: generate short tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          inputs: [{name: git-repo}]
          outputs: [{name: git-repo}]
          run:
            path: ash
            args:
              - -c
              - sed 's/^v//' esh-release/tag > esh-release/short-tag
      - load_var: short-tag
        file: esh-release/short-tag
      - put: esh-image
        params:
          build: git-repo/esh
          additional_tags: esh-release/version
          build_args:
            VERSION: ((short-tag))
        on_failure: &on_failure
          put: build-status
          params: {state: failure, commit: git-repo}
        on_error: *on_failure
        on_abort: *on_failure
      - put: build-status
        params: {state: success, commit: git-repo}
