resources:
  - name: mumble-image
    type: docker-image
    icon: docker
    source:
      repository: registry.barth.tech/library/mumble
      username: ((registry.username))
      password: ((registry.password))

jobs:
  - name: build-mumble
    plan:
      - get: git-repo
        trigger: true
        passed: [update-pipeline]
      - put: build-status
        params: {state: pending, commit: git-repo}
      - put: mumble-image
        params:
          build: git-repo/mumble
          additional_tags: git-repo/mumble/tags
        on_failure: &on_failure
          put: build-status
          params: {state: failure, commit: git-repo}
        on_error: *on_failure
        on_abort: *on_failure
      - put: build-status
        params: {state: success, commit: git-repo}
