["0.1.1".args]
"VERSION" = "0.1.1"

["0.2.0".args]
"VERSION" = "0.2.0"

["0.3.1".args]
"VERSION" = "0.3.1"

["0.3.2".args]
"VERSION" = "0.3.2"

["0.1.0".args]
"VERSION" = "0.1.0"

["0.3.0".args]
"VERSION" = "0.3.0"

["latest".args]
"VERSION" = "0.3.2"
