resources:

  - name: git-repo
    icon: github
    type: git
    source:
      uri: git@github.com:r-bar/images.git
      branch: master
      private_key: ((git-config.ssh-private-key))
    webhook_token: ((webhook-token))
    check_every: 24h

  - name: build-status
    type: github-status
    icon: list-status
    source:
      owner: r-bar
      repository: images
      access_token: ((github-access-token))

jobs:
  - name: update-pipeline
    plan:
      - get: git-repo
        trigger: true

      - task: generate-full-pipeline
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          inputs: [{name: git-repo}]
          outputs: [{name: git-repo}]
          run:
            path: ash
            args:
              - -c
              - |
                set -e
                apk add --no-progress make python3 py3-yaml
                cd git-repo
                make ci/full-pipeline.yaml

      - set_pipeline: self
        file: git-repo/ci/full-pipeline.yaml
