---
resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: registry.barth.tech/library/concourse_github_status
      tag: latest

resources:

  - name: git-repo
    icon: github
    type: git
    source:
      uri: git@github.com:r-bar/images.git
      branch: master
      private_key: ((git-config.ssh-private-key))
    webhook_token: ((webhook-token))
    check_every: 24h

  #- name: build-status
  #  type: github-status
  #  icon: list-status
  #  source:
  #    owner: r-bar
  #    repository: images
  #    access_token: ((github-access-token))

jobs:
  - name: update-pipeline
    plan:
      - get: git-repo
        trigger: true

      - task: generate-full-pipeline
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          inputs: [{name: git-repo}]
          outputs: [{name: git-repo}]
          run:
            path: ash
            args:
              - -c
              - |
                set -e
                apk add --no-progress python3 jsonnet
                cd git-repo
                ./build.py images > ci/images.json
                jsonnet ci/build-and-push.jsonnet > ci/full-pipeline.yaml

      - set_pipeline: self
        file: git-repo/ci/full-pipeline.yaml
