apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: images-ci
spec:
  entrypoint: pipeline
  templates:
    - name: pipeline
      steps:
        - - name: clone
            templateRef:
              name: git
              template: clone
            arguments:
              parameters:
                - name: repo-url
                  value: 'https://github.com/r-bar/images.git'
                - name: revision
                  value: master

        - - name: list-images
            template: list-images
            arguments:
              artifacts:
                - name: repo
                  from: '{{steps.clone.outputs.artifacts.repo}}'

        - - name: build
            templateRef:
              name: kaniko
              template: build-and-push-image
            arguments:
              artifacts:
                - name: context
                  from: '{{steps.clone.outputs.artifacts.repo}}'
              parameters:
                - name: dockerfile
                  value: '{{item.dockerfile}}'
                - name: context-path
                  value: '{{item.context}}'
                - name: image-name
                  value: '{{item.repository}}'
                - name: image-tag
                  value: '{{item.tag}}'
                - name: build-args-file
                  value: '{{item.tagFile}}'
            withParam: '{{steps.list-images.outputs.result}}'

    - name: list-images
      inputs:
        artifacts:
          - name: repo
            path: /repo
      container:
        image: registry.barth.tech/library/utility
        command: [python, build.py, images]
        workingDir: /repo

    - name: git-clone
      inputs:
        parameters:
          - name: repo-url
          - name: revision
      outputs:
        artifacts:
          - name: repo
            path: /repo
      container:
        image: registry.barth.tech/library/utility
        command:
          - 'git'
          - 'clone'
          - '--recurse-submodules'
          - '--depth=1'
          - '--branch={{inputs.parameters.revision}}'
          #- --branch=master
          - '{{inputs.parameters.repo-url}}'
          #- https://github.com/r-bar/images.git
          - 'repo'
